POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "username": "minh",
  "password": "minh"
}

###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "username": "minh",
  "password": "minh"
}
###
POST http://localhost:5000/api//api/products
Content-Type: application/json

{
  "title": "React",
  "description": "React",
  "url": "react.com",
  "status": "TO LEARN"
}

